#!/bin/sh

mount /media/cdrom
cd /
cp /media/cdrom0/simple-cdd/urna_extras.tar.gz /opt/
umount /media/cdrom0

tar -zxf /opt/urna_extras.tar.gz
/usr/sbin/update-grub

useradd keyboarduser -p 9875$RANDOM -m

chown -R www-data:www-data /var/www
chown -R www-data:www-data /srv
chown -R keyboarduser /opt/keyboard-websocket

/usr/sbin/dmidecode | grep -i product | grep VirtualBox && bash /opt/VBoxLinuxAdditions.run --nox11

a2enmod rewrite

cd /opt/keyboard-websocket
pip install --no-index -f packages -r requirements.txt

exit 0
